- name: Make sure we have a 'deployers' group
  group:
    name: deployers
    state: present

- name: Allow 'deployers' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%deployers'
    line: '%deployers ALL=(ALL) NOPASSWD: ALL'

- name: Add sudoers users to deployers group
  user: name=deploy groups=deployers append=yes state=present shell=/bin/zsh

- name: Set up authorized keys for the deployer user
  authorized_key:
    user: deploy
    key: https://github.com/emilioeduardob.keys

- name: Create basic zsh config
  file: name="/home/deploy/.zshrc" state=touch owner=deploy group=deploy
