---
- name: Downloading and enable the EPEL repository definitions.
  yum: name=epel-release state=present

- name: Install basic packages
  yum: name={{item}} state=present
  with_items:
    - openssl
    - curl
    - git
    - vim
    - htop
    - zsh
